datadir: val_large
indir: ${location.root_dir}/${datadir}
outdir: ${location.out_dir}/${datadir}/random_thick_256

n_jobs: 8

generator_kind: random

mask_generator_kwargs:
  irregular_proba: 1
  irregular_kwargs:
    min_times: 1
    max_times: 5
    max_width: 100
    max_angle: 4
    max_len: 200

  box_proba: 0.3
  box_kwargs:
    margin: 10
    bbox_min_size: 30
    bbox_max_size: 150
    max_times: 3
    min_times: 1

  segm_proba: 0
  squares_proba: 0

  variants_n: 5

max_masks_per_image: 1

cropping:
  out_min_size: 256
  handle_small_mode: upscale
  out_square_crop: True
  crop_min_overlap: 1

max_tamper_area: 0.5

defaults:
  - location: mml7-places
